# Generated by Django 2.2 on 2021-07-16 05:12

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='Expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 7, 12, 3, 512871), null=True),
        ),
    ]
