# Generated by Django 2.2 on 2021-07-16 05:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0002_auto_20210716_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published',
        ),
        migrations.AlterField(
            model_name='borrower',
            name='Expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 7, 14, 25, 84633), null=True),
        ),
    ]
