# Generated by Django 2.2 on 2021-07-16 05:15

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0003_auto_20210716_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.CharField(help_text='Enter the year of publication', max_length=4, null=True,
                                   verbose_name='Published Year'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='Expire_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 7, 15, 43, 828041), null=True),
        ),
    ]
